name: MincraMagics
version: ${project.version}
main: jp.mincra.mincramagics.MincraMagics
api-version: 1.13
authors: [Harineko]
depend: [NBTAPI]

commands:
  mcr:
    description: MincraMagicsのコマンド。
    usage: /<command>
  skill:
    description: マテリアルに関するコマンド。
    usage: /<command>
  translate:
    description: チャットの翻訳を行うコマンド。
    aliases: tr
    usage: /<command> [ja, en, ...] [ja, en, ...] [TEXT]